In [405]:
import numpy as np

In [433]:
revenue = np.array([[180,200,220],[24,36,40],[12,18,20]])
expenses = np.array([[80,90,100],[10,16,20],[8,10,10]])

In [434]:
revenue

array([[180, 200, 220],
       [ 24,  36,  40],
       [ 12,  18,  20]])

In [417]:
profit = revenue - expenses

In [418]:
profit

array([[100, 110, 120],
       [ 14,  20,  20],
       [  4,   8,  10]])

In [429]:
# matrix multiplication


unit_price = np.array([1000,400,1200])
unit_sale = np.array([[80,90,100],[10,16,20],[8,10,10]])



np.dot(unit_price, unit_sale)

array([ 93600, 108400, 120000])

In [431]:
# when we multipllly directelly it gives the ans in the form of matrix

total_sale = unit_price*unit_sale
total_sale   
# see the ans it is 2d matrix and we want the dot product so we apply the dot product funtion from the numpyv

array([[ 80000,  36000, 120000],
       [ 10000,   6400,  24000],
       [  8000,   4000,  12000]])

In [432]:
# exercise by code basicss.....

In [440]:
# 1. revenue of the company represented inthe form of USD and have to convert all rows and column with in INR

company_revenue = np.array([[200,200,250],[68,79,105],[110,140,180],[80,85,90]])
INR = 75

revenue_INR = company_revenue* INR
revenue_INR

array([[15000, 15000, 18750],
       [ 5100,  5925,  7875],
       [ 8250, 10500, 13500],
       [ 6000,  6375,  6750]])

array([180])

In [441]:
# 2..finding the total sum of given matrix 

In [444]:
price_per_unit = np.array([20,30,15])
unit_sold = np.array([[50,60,25],[10,13,5],[40,70,52]])

np.dot(price_per_unit,unit_sold)

array([1900, 2640, 1430])