In [1]:
# model importing
import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding

In [2]:
reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

# label for food reviews
sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [3]:
# already import hot one hot encoding what it will do its convert the text into the vector. using vocablary number which providing by us..


one_hot("amazing restaurant",30)
        #(review, vocablary(rang))
        #(amazing restuarant : 2 words then it gives output to in range of vocablary)


[17, 10]

In [15]:
# simlary apply one hot econding on all of the word which are available in review..
vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
encoded_reviews

[[11, 12],
 [17, 10],
 [10, 15],
 [20, 15, 15],
 [14, 9, 19],
 [4, 12],
 [13, 9, 8],
 [20, 14],
 [20, 12],
 [21, 8]]

In [16]:
# padding is must important becuase we can see in out encoding_review every vector size is not equal some of the vector contains 2 or 3
# padding is predifind fuction in keras it will managed the size of vector.


max_length = 4
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
padded_reviews

array([[11, 12,  0,  0],
       [17, 10,  0,  0],
       [10, 15,  0,  0],
       [20, 15, 15,  0],
       [14,  9, 19,  0],
       [ 4, 12,  0,  0],
       [13,  9,  8,  0],
       [20, 14,  0,  0],
       [20, 12,  0,  0],
       [21,  8,  0,  0]])

In [17]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [20]:

X = padded_reviews
y = sentiment

X

array([[11, 12,  0,  0],
       [17, 10,  0,  0],
       [10, 15,  0,  0],
       [20, 15, 15,  0],
       [14,  9, 19,  0],
       [ 4, 12,  0,  0],
       [13,  9,  8,  0],
       [20, 14,  0,  0],
       [20, 12,  0,  0],
       [21,  8,  0,  0]])

In [22]:

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
model.summary()

Model: "sequential_1"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding (Embedding)           │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten_1 (Flatten)             │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [23]:
model.fit(X, y, epochs=50, verbose=0)

In [24]:
# evaluate the model
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 180ms/step - accuracy: 1.0000 - loss: 0.6404


1.0

In [25]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [26]:

weights[13]

array([ 0.05661901, -0.0128834 ,  0.00092092,  0.00581761, -0.08241712],
      dtype=float32)

In [27]:
weights[4]

array([ 0.10381016, -0.02105789,  0.01809295,  0.03014718, -0.08262912],
      dtype=float32)

In [28]:
weights[16]

array([-0.0487939 , -0.03293469,  0.03680838,  0.03997331, -0.00092574],
      dtype=float32)