In [4]:
import tensorflow_hub as hub
import tensorflow_text as text

In [5]:
preprocess_url = "https://tfhub.dev/tensorflow/bert_en_uncased_preprocess/3" # bert preprocess model url
encoder_url = "https://tfhub.dev/tensorflow/bert_en_uncased_L-12_H-768_A-12/4" # encoding url of bert

In [11]:
#making hub layer and pass url of preprocess model(BERT)#
bert_preprocess_model = hub.KerasLayer(preprocess_url)

In [16]:
text_test = ['nice movie indeed','i love python programing']#statment for the preprocess#
text_preprocessed = bert_preprocess_model(text_test)#pass the statment in preprocessed function #
text_preprocessed.keys()

dict_keys(['input_mask', 'input_word_ids', 'input_type_ids'])

In [17]:
text_preprocessed['input_mask']

<tf.Tensor: shape=(2, 128), dtype=int32, numpy=
array([[1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])>

In [18]:
bert_model = hub.KerasLayer(encoder_url)
bert_result = bert_model(text_preprocessed)
bert_result.keys()

dict_keys(['sequence_output', 'encoder_outputs', 'default', 'pooled_output'])

In [19]:
#embedding result#
bert_result['pooled_output']

<tf.Tensor: shape=(2, 768), dtype=float32, numpy=
array([[-0.7917741 , -0.21411933,  0.49769458, ...,  0.2446516 ,
        -0.47334474,  0.8175871 ],
       [-0.8998869 , -0.5022243 , -0.8014913 , ..., -0.60264313,
        -0.69911593,  0.90730995]], dtype=float32)>

In [20]:
bert_result['sequence_output']
#shope = 2 (nice movie indeed,i love python), 128 = paddig size 2, 768 = vector size.#

<tf.Tensor: shape=(2, 128, 768), dtype=float32, numpy=
array([[[ 0.07292046,  0.08567803,  0.14476834, ..., -0.09677116,
          0.08722133,  0.07711101],
        [ 0.17839415, -0.1900607 ,  0.50349444, ..., -0.05869861,
          0.327171  , -0.1557856 ],
        [ 0.18701461, -0.4338877 , -0.48875138, ..., -0.15502766,
          0.00145099, -0.24470963],
        ...,
        [ 0.12083066,  0.12884238,  0.46453527, ...,  0.07375523,
          0.17441952,  0.16522099],
        [ 0.07967862, -0.01190662,  0.502254  , ...,  0.13777755,
          0.210022  ,  0.00624555],
        [-0.07212693, -0.28303438,  0.59033406, ...,  0.47551903,
          0.16668476, -0.08920355]],

       [[ 0.040605  ,  0.3267148 , -0.06604569, ..., -0.11767734,
          0.20420271,  0.60382676],
        [ 0.42078888,  0.38885817, -0.19671658, ..., -0.25060484,
          0.2919652 ,  0.34592423],
        [ 1.049667  ,  1.085755  ,  0.4954929 , ...,  0.31622744,
          0.2740115 ,  0.26547587],
        ...,